### ISSUE TITLE
pt top from console errors

### ISSUE THREAD

**Issue by TymekSL** [CodedRed-Spigot/PlayTimes#52]
UUID Lookup Type: true
pt top
[01:36:03 WARN]: Unexpected exception while parsing console command "pt top"
org.bukkit.command.CommandException: Unhandled exception executing command 'pt' in plugin Playtimes v1.6.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:987) ~[paper-1.20.4.jar:git-Paper-370]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchServerCommand(CraftServer.java:972) ~[paper-1.20.4.jar:git-Paper-370]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:500) ~[paper-1.20.4.jar:git-Paper-370]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-370]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1518) ~[paper-1.20.4.jar:git-Paper-370]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.20.4.jar:git-Paper-370]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-370]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: org.bukkit.command.CommandException: Unhandled exception executing command 'toppt' in plugin Playtimes v1.6.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:987) ~[paper-1.20.4.jar:git-Paper-370]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:1074) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at me.codedred.playtimes.commands.Time.handleTopCommand(Time.java:207) ~[PlayTimes-1.6.1.jar:?]
        at me.codedred.playtimes.commands.Time.onCommand(Time.java:54) ~[PlayTimes-1.6.1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 9 more
Caused by: java.lang.ClassCastException: class com.destroystokyo.paper.console.TerminalConsoleCommandSender cannot be cast to class org.bukkit.entity.Player (com.destroystokyo.paper.console.TerminalConsoleCommandSender and org.bukkit.entity.Player are in unnamed module of loader java.net.URLClassLoader @5ce65a89)
        at me.codedred.playtimes.commands.TopTime.onCommand(TopTime.java:78) ~[PlayTimes-1.6.1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:987) ~[paper-1.20.4.jar:git-Paper-370]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:1074) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at me.codedred.playtimes.commands.Time.handleTopCommand(Time.java:207) ~[PlayTimes-1.6.1.jar:?]
        at me.codedred.playtimes.commands.Time.onCommand(Time.java:54) ~[PlayTimes-1.6.1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 9 more

pt top from console

**Comment by CodedRedGIT** [comment]
Can you run /pt version and paste the output here. Thank you for reporting.

**Comment by CodedRedGIT** [comment]
Need further information. Please make a new ticket if you are still experiencing issues.
